#!/usr/bin/env node
/**
 * THIRD_PARTY_NOTICES 生成器（backlog D8；Node 零新依赖，与 `bridge/schema/generate.mjs` 同手法）。
 *
 * **为什么需要生成而不是手写**：随包二进制与素材的版本事实来源是
 * `node-runtime-build/VERSIONS.env`（Node / NDK / OpenCV / KleidiCV / npm 全部钉死在那里）。
 * 手写的声明文件必然在某次版本变更后与事实脱节 —— 而许可声明脱节在分发时是**法律问题**，
 * 不是文档瑕疵。VERSIONS.env 改了而本文件没改，本门（以及 CI 的 `--check`）当场红。
 *
 * **许可文本本身不生成**：`licenses/` 目录放的是各上游**逐字**许可原文，随生成物入库。
 * 本脚本只负责「哪几个组件、什么版本、从哪条交付轨出去的、许可叫什么、原文在哪」——
 * 即清单面。原文与清单分开，是因为原文不该被脚本改写（改了就等于伪造上游许可），
 * 而清单必须与 VERSIONS.env 联动。
 *
 * 门：
 *   - `node gen-notices.mjs --check` —— 入库的 `THIRD_PARTY_NOTICES.md` 与 VERSIONS.env 同步；
 *   - CI：`node gen-notices.mjs && git diff --exit-code`（照抄 js-tests 的 gen:wire 形状）。
 *
 * 路径以本文件位置为锚（不依赖 CWD），可从任意目录调用。
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..', '..')
const VERSIONS_PATH = path.join(ROOT, 'node-runtime-build/VERSIONS.env')
const OUT = path.join(ROOT, 'THIRD_PARTY_NOTICES.md')

/**
 * VERSIONS.env 是 shell 源文件（有一行 `WORK_DIR="${WORK_DIR:-/build}"` 带插值），
 * 所以不能用 shell source —— 只认 `KEY=VALUE` 的字面量行，注释与插值行跳过。
 * 与 `build-opencv.sh` 的 `source` 读同一份文件，但**只取**本脚本要用的键。
 */
function readVersions() {
  const out = {}
  for (const line of fs.readFileSync(VERSIONS_PATH, 'utf8').split('\n')) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim())
    if (!m) continue
    out[m[1]] = m[2]
  }
  return out
}

const V = readVersions()

/** 缺钉死的键即红：声明文件里出现 "undefined" 比没有声明更糟。 */
function need(key) {
  const v = V[key]
  if (!v) throw new Error(`VERSIONS.env 缺 ${key}（THIRD_PARTY_NOTICES 的版本事实来源少了一根钉）`)
  return v
}

const NODE_VERSION = need('NODE_VERSION')
const NPM_CLI_VERSION = need('NPM_CLI_VERSION')
const NDK_VERSION = need('NDK_VERSION')
const OPENCV_VERSION = need('OPENCV_VERSION')
const OPENCV_COMMIT = need('OPENCV_COMMIT')
const KLEIDICV_COMMIT = need('KLEIDICV_COMMIT')
const ANDROID_API = need('ANDROID_API')
const TARGET_ARCH = need('TARGET_ARCH')

/**
 * 组件表。`file` 字段是 `licenses/` 下的原文路径 —— 生成器**不校验文件存在**
 * （`--check` 也不），因为本门管的是「清单 ↔ VERSIONS.env」这一条联动；
 * 原文在不在由**文档链接门**（`check-doc-links.sh`，会顺着清单里的链接查）与
 * `prepareNoticesAssets` 的逐件 require 两处分别管。
 *
 * `libjpeg-turbo` 一项是**子目录**（`libjpeg-turbo/LICENSE.md`）而不是同层文件 ——
 * 上游自己的 LICENSE.md 里有一条指向 `README.ijg` 的相对链接（IJG 许可原文就在那份里），
 * 拍平到一层会让那条链接断，文档链接门当场红（2026-10-01 首次提交实测撞到过：
 * 本机那份 1586 行的旧 LICENSE 在 CI 上多出 9 条链接，链接门抓到的就是它）。
 */
const COMPONENTS = [
  {
    name: 'Node.js',
    version: `${NODE_VERSION}（含 vendored npm ${NPM_CLI_VERSION}）`,
    license: 'MIT（npm 段为 Artistic License 2.0，逐字列在原文对应节）',
    file: 'node-LICENSE',
    shipsAs: [
      '`lib/arm64-v8a/libnode.so`（jniLibs，随包）',
      '`lib/arm64-v8a/libnoden.so`（`:engine:node-process` 的进程宿主；noden 改名入 jniLibs —— PackageManager 只提取 `*.so`，而 exec 要真文件，见 `autoscript.engine-natives`）',
      '`assets/npm/**` → `filesDir/npm/`（vendored npm CLI，见 §10.2 调用链首段）',
    ],
  },
  {
    name: 'Android NDK / libc++',
    version: `${NDK_VERSION}（bionic API ${ANDROID_API}，${TARGET_ARCH}）`,
    license: 'Apache License 2.0 **WITH LLVM-exception**（NDK 工具链本体另有第三方条款，见其 NOTICE）',
    file: null,
    shipsAs: ['`lib/arm64-v8a/libc++_shared.so`（libnode 的传递依赖，readelf 实证）'],
  },
  {
    name: 'OpenCV（静态链接进 libopencv.so）',
    version: `${OPENCV_VERSION}（commit \`${OPENCV_COMMIT}\`）`,
    license: 'Apache License 2.0',
    file: 'opencv-LICENSE',
    shipsAs: ['`lib/arm64-v8a/libopencv.so`（`:bridge:image`，§9.2 图像管线）'],
  },
  {
    name: 'KleidiCV（OpenCV 的 AArch64 HAL）',
    version: `${KLEIDICV_COMMIT}（软降级：下载失败则不启用，结论写进 SHASUMS256 审计行）`,
    license: 'Apache License 2.0',
    file: 'kleidicv-LICENSE',
    shipsAs: ['同 `libopencv.so`（静态归档进同 so）'],
  },
  {
    name: 'libjpeg-turbo（OpenCV 的 JPEG 编解码）',
    version: '随 OpenCV 源码树 pin（`3rdparty/libjpeg-turbo`，commit `a99141acd7874bfe027d2bd945a4bd1d7192178b`）',
    license: 'IJG License **或** Modified (3-clause) BSD —— 双许可，取哪个由使用者自选',
    file: 'libjpeg-turbo/LICENSE.md',
    shipsAs: ['同 `libopencv.so`（`BUILD_JPEG=ON` 强制走树内源码）'],
  },
  {
    name: 'libpng（OpenCV 的 PNG 编解码）',
    version: '随 OpenCV 源码树 pin（`3rdparty/libpng`，commit `8472efd791dba6cd53ff5f73fe3ceb874856b454`）',
    license: 'PNG Reference Library License version 2',
    file: 'libpng-LICENSE',
    shipsAs: ['同 `libopencv.so`（`BUILD_PNG=ON` 强制走树内源码）'],
  },
  {
    name: 'zlib（OpenCV 的压缩层）',
    version: '随 OpenCV 源码树 pin（`3rdparty/zlib`，commit `266a2989b234a84129c04219f06099164378c280`）',
    license: 'zlib License',
    file: 'zlib-LICENSE',
    shipsAs: ['同 `libopencv.so`（`BUILD_ZLIB=ON` 强制走树内源码）'],
  },
]

function render() {
  const L = []
  L.push('# 第三方许可声明（THIRD_PARTY_NOTICES）')
  L.push('')
  L.push('<!-- AUTO-GENERATED by node-runtime-build/licenses/gen-notices.mjs — DO NOT EDIT.')
  L.push('     源：node-runtime-build/VERSIONS.env（版本事实来源）+ 同目录 licenses/（上游逐字许可原文）。')
  L.push('     再生成：node node-runtime-build/licenses/gen-notices.mjs（漂移由 --check 与 CI 门看着）。 -->')
  L.push('')
  L.push('本文件是**清单面**：哪几个第三方组件、什么版本、经哪条交付轨随包、许可叫什么、原文在哪。')
  L.push('许可**原文**逐字放在 [`node-runtime-build/licenses/`](node-runtime-build/licenses/)，不在本文件里转述 ——')
  L.push('转述即失真。各组件的**完整**第三方条款（Node 的 ICU/依赖条款、NDK 工具链的第三方清单等）')
  L.push('以原文为准，本清单不替代原文。')
  L.push('')
  L.push('**生成而非手写的原因**：版本钉死在 `VERSIONS.env`，手写声明必然在某次版本变更后与事实脱节，')
  L.push('而许可声明脱节在分发时是法律问题。改 `VERSIONS.env` 而没跑本脚本 = 门红。')
  L.push('')
  L.push('## 1. 组件清单')
  L.push('')
  L.push('| 组件 | 版本 | 许可 | 随包形态 |')
  L.push('|---|---|---|---|')
  for (const c of COMPONENTS) {
    const file = c.file ? `见 [原文](node-runtime-build/licenses/${c.file})` : '见 NDK 随附 NOTICE（未随包）'
    L.push(`| ${c.name} | ${c.version} | ${c.license} | ${file} |`)
  }
  L.push('')
  L.push('## 2. 各组件的随包位置（随包 = 进了 APK 或落进 filesDir）')
  L.push('')
  for (const c of COMPONENTS) {
    L.push(`### ${c.name} — ${c.version}`)
    L.push('')
    for (const s of c.shipsAs) L.push(`- ${s}`)
    L.push('')
  }
  L.push('## 3. 本仓自有代码')
  L.push('')
  L.push('AutoScript 自身的 Kotlin / C++ / TypeScript 源码是 **GPL-2.0-or-later**，见\n[`LICENSE`](LICENSE)。')
  L.push('上面列的是**随包分发的第三方二进制与素材**，不含本仓源码。')
  L.push('')
  L.push('## 4. 不在随包范围（故不在上面清单里）')
  L.push('')
  L.push('- 开发期依赖（Gradle / npm devDependencies / NDK 构建工具链本身）不随包分发，不需随包声明。')
  L.push('- `bridge/js` 标 `"private": true`、不发布到 registry；其依赖树不随 APK 分发。')
  L.push('')
  L.push('## 5. 维护口径')
  L.push('')
  L.push('- **换版本 = 一件事一个提交**（`VERSIONS.env` 顶部纪律）：改版本后必须重跑本脚本并同提交更新。')
  L.push('- 新增随包二进制/素材时：**先加组件行 + 放逐字原文**，再改打包任务 —— 顺序反了会出现')
  L.push('  「已随包但无声明」的窗口。')
  L.push('- 组件缺席时如实写「未随包」而不是删行：清单要反映事实，不是反映愿望。')
  L.push('')
  return L.join('\n')
}

const rendered = render()
if (process.argv.includes('--check')) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
  if (cur !== rendered) {
    console.error('✗ THIRD_PARTY_NOTICES.md 与 VERSIONS.env 不同步：跑 `node node-runtime-build/licenses/gen-notices.mjs`')
    process.exit(1)
  }
  console.log(`THIRD_PARTY_NOTICES 同步门：${COMPONENTS.length} 个组件，逐字一致。`)
} else {
  fs.writeFileSync(OUT, rendered)
  console.log(`已写 ${path.relative(ROOT, OUT)}（${COMPONENTS.length} 个组件）`)
}
